# Server name (displayed in the AirPlay device list)
airplay.serverName=Mukar

# Video resolution settings
airplay.width=1920
airplay.height=1080
airplay.fps=60

# Player selection (gstreamer, ffmpeg, vlc, h264-dump)
player.implementation=gstreamer

# Start the GStreamer video window in borderless fullscreen mode
player.gstreamer.fullscreen=false

# Whether to enable menu control
player.tray.enabled=true
