# Server name (displayed in the AirPlay device list)
airplay.serverName=Mukar

# Video resolution settings
airplay.width=3840
airplay.height=2160
airplay.fps=60

# Player selection (gstreamer, ffmpeg, vlc, h264-dump)
player.implementation=gstreamer

# Start the GStreamer video window in borderless fullscreen mode
player.gstreamer.fullscreen=true

# Whether to enable menu control
player.tray.enabled=true

launcher.language=en-US

launcher.autoStart.enabled=false
launcher.autoStart.runService=false

