# 服务器名称（在AirPlay设备列表中显示的名称）
airplay.serverName=Mukar

# 视频分辨率设置
airplay.width=1920
airplay.height=1080
airplay.fps=60

# 播放器选择（gstreamer, ffmpeg, vlc, h264-dump）
player.implementation=gstreamer

# 是否启用菜单控制
player.menu.enabled=true